name: regodon_labact1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  # important !
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# important !
flutter:
  assets:
    - assets/icons/superpogi.jpg
    - assets/images/logo.png
    - assets/images/pogi.jpg
    - assets/images/bebi.jpg
    - assets/images/Image.jpg
    - assets/images/Image1.jpg
    - assets/images/Image2.jpg
    - assets/images/Image3.jpg
  uses-material-design: true