name: regodon_labact1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # important !
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# important !
flutter:
  assets:
    - assets/icons/superpogi.jpg
    - assets/images/pogi.jpg
  uses-material-design: true